### ISSUE TITLE
Pass the parcel

### ISSUE THREAD

**Issue by lily-law** [chingu-voyages/v18-geckos-team-02#31]
Every few days we could merge in our branches into a 'parcel' branch, then each of us will be assigned this issue in turn. It will be the assigns role to either: 
- Fix things
- Refactor to make things simpler (and better but simpler first)
- Comment on code that need improvement/refactoring

**Comment by jondhill333** [comment]
Seconded accumulation testing notes

Add note modal

**- Gets “invalid date” displayed on main unless you select “custom” in date and tag selector (on either individual file or group upload) - this appears to be because app is defaulting to date modified in the code if no date selected but notes don’t generate with a date modified (this is blank in date and tags editor display for notes)** SOLVED (App.js line 89/90) - modified: doesn't exist on note file, so made ternary operator to implement dateNow if modified is empty.

** if attempting to add more than one note at a time, only one note will display on the main - the last one created. If attmepting to add notes one at a time, only the last one created will display**
IN PROGESS - issue #35

**- app reports error if tags field is entered into** IN PROGESS - issue #36


UPLOAD MODAL

**- If attempting to upload files one by one, will delete out of main the existing file - this occurs whether it is of the same or different type. if attempting to add more than one file at a time, only one file will display on the main - the last one created.**
IN PROGESS - issue #35

**- app reports error if tags field is entered into** IN PROGESS - issue #36

1. -  defaulting date and time to modified - we don’t have functionality of adding the file for day of upload (i.e. today's) date: 
**Action:** Up for discussion/final decision on Tuesday.

2. - ~~ If one file is displaying on main, if you click upload files, then cancel in the browser implemented box, the file upload modal appears anyway with disabled upload button.~~ No cancel/back button (edited) -
Action:**  **RESOLVED: (issue #38)**

3. - upload modal is pushing main down main instead of laying over it. **Action: Issue #46 RESOLVED**

4. - Doesn’t recognise xd files - won’t display on main **Action: Issue #51 IN PROGRESS**

5. - had issue handling file size - jpeg and png appearing very large - not sure of size handling in display **incorrect - size handling is done**
6. App allowing user to upload the same file multiple times. **Action: Issue #49 IN PROGRESS**
7.  `<main>` tag not enclosing all of app major sections/areas. See Developer Tools --> Elements. **Action: Issue #47 RESOLVED**
